apiVersion: v1
kind: Deployment
metadata:
  name: app1
spec:
  containers:
  - name: app1
    image: paulbouwer/hello-kubernetes
metadata:
  name: app2
spec:
  containers:
  - name: app2
    image: paulbouwer/hello-kubernetes
metadata:
  name: app3
spec:
  containers:
  - name: app3
    image: paulbouwer/hello-kubernetes
