apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-one
spec:
  rules:
  - http:
    paths:
    - path: 
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app-one
# spec:
#   selector:
#     app: app1
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9376