# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Use a box that supports libvirt
    config.vm.box = "generic/ubuntu2204"
    
    # Define the server (controller) VM
    config.vm.define "npaolettS" do |server|
      server.vm.hostname = "npaolettS"
      server.vm.network "private_network", ip: "192.168.56.110"
      
      # VM resources configuration
      server.vm.provider "libvirt" do |lv|
        lv.memory = 512
        lv.cpus = 1
      end
      
      # Provisioning script for the server node
      server.vm.provision "shell", path: "scripts/server_setup.sh"
    end
    
    # Define the server worker VM
    config.vm.define "npaolettSW" do |worker|
      worker.vm.hostname = "npaolettSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      
      # VM resources configuration
      worker.vm.provider "libvirt" do |lv|
        lv.memory = 512
        lv.cpus = 1
      end
      
      # Provisioning script for the worker node
      worker.vm.provision "shell", path: "scripts/worker_setup.sh"
    end
  end